<a href="https://colab.research.google.com/github/elaheJ/ClassExercises/blob/main/CPM_PERT_Shortened.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#CPM PERT using the randomly generated data from Monday

import pandas as pd

simulationDF=pd.read_csv("/content/drive/MyDrive/496/simulationDataset.csv")
simulationDF.head(2)

,A,B,C,D,E,F,G,H,I,J,EOP
0,6.080954,4.087029,2.231355,2.275579,7.699553,2.870247,3.331707,8.836049,9.390602,3.210852,NaN
1,6.009382,4.367142,3.657515,2.765880,5.697688,3.217564,3.222966,6.638556,19.329857,2.902558,NaN

In [5]:
paths=['ADEJ','BCDEJ','BCFGJ','BCFHJ','BI']
pathsDF=pd.DataFrame(columns=paths)

ADEJ=[]
BCDEJ=[]
BCFGJ=[]
BCFHJ=[]
BI=[]
for  index, row in simulationDF.iterrows():
  ADEJ.append(row['A']+row['D']+row['E']+row['J'])
  BCDEJ.append(row['B']+row['C']+row['D']+row['E']+row['J'])
  BCFGJ.append(row['B']+row['C']+row['F']+row['G']+row['J'])
  BCFHJ.append(row['B']+row['C']+row['F']+row['H']+row['J'])
  BI.append(row['B']+row['I'])

pathsDF['ADEJ']=ADEJ
pathsDF['BCDEJ']=BCDEJ
pathsDF['BCFGJ']=BCFGJ
pathsDF['BCFHJ']=BCFHJ
pathsDF['BI']=BI

pathsDF.head(2)

#new code
pathsDF['critical']=pathsDF.idxmax(axis=1)

#new code
print(pathsDF.critical.value_counts())

BCDEJ    33984
BCFGJ    25497
BI       21849
BCFHJ    14802
ADEJ      3868
Name: critical, dtype: int64